### ISSUE TITLE
Propertization of modeline is jarring

### ISSUE THREAD

**Issue by swflint** [unhammer/org-upcoming-modeline#1]
Propertizing the mode line to follow org-3 is a bit jarring.  Perhaps another face would be better?

**Comment by unhammer** [comment]
I guess https://github.com/unhammer/org-upcoming-modeline/commit/a8930f43d5b25e2767e55812b9c4bca51beda629 should fix this, or do you have a better suggestion for a default face?

**Comment by swflint** [comment]
I have an idea, I just have to play around with it a bit.  I figured I'd make an issue while I worked on it.

**Comment by unhammer** [comment]
I like it :) Closed by 8ce00793a9a55604ed1bcbb8d46596e24b4eb63e
