### ISSUE TITLE
`Error (org-ql-select): Not an Org buffer`

### ISSUE THREAD

**Issue by morgandavidson** [unhammer/org-upcoming-modeline#14]
When `org-upcoming-modeline` is enabled, instead of showing the next upcoming org appointment, the modeling shows: `*invalid*`. Also, I have the following error when Emacs starts: `Error (org-ql-select): Not an Org buffer`.

I use Emacs 29 and a specific state for appointments: `MEETING`.

I define states as follows: 

```emacs-lisp
(setq org-todo-keywords
  '((sequence
    "INBOX(i)"
    "BACKLOG(b)"
    "NEXT(n)"      
    "MEETING(m)"
    "RECURRENT(r)"
    "STARTED(s)"
    "WAITING(w)"
    "DELEGATED(l)"
    "|"
    "DONE(d)"
    "DEFERRED(f)"
    "CANCELLED(c)"
)))
```

**Comment by unhammer** [comment]
org-upcoming-modeline runs
`                (org-ql-select (org-agenda-files) …`
What does `(org-agenda-files)` contain? Can you `M-: (org-ql-select (org-agenda-files) "test")` ? (That should search your org headings for the string "test").

You could also try to `M-x toggle-debug-on-error` and run `M-x org-upcoming-modeline` twice (to turn it off and on again)

**Comment by morgandavidson** [comment]
`org-agenda-files`:
```emacs-lisp
(setq org-agenda-files (list                               
                        (concat orgzly-path ".inbox.org")  
                        (concat captures-path "inbox.org") 
                        (concat orgzly-path "meetings.org")
                        (concat orgzly-path "projects.org")
                        (concat orgzly-path "ToDo.org")    
                        )                                  
      )                                                    
```

`M-: (org-ql-select (org-agenda-files) "backup") `:

```
((headline (:raw-value "Backup Calibre" :begin 15429 :end 15486 :pre-blank 0 :contents-begin 15454 :contents-end 15486 ...)) (headline (:raw-value "[1/1] Backups" :begin 20088 :end 20341 :pre-blank 0 :contents-begin 20106 :contents-end 20340 ...)) (headline (:raw-value "Add new folders to syncthing" :begin 20106 :end 20341 :pre-blank 0 :contents-begin 20150 :contents-end 20340 ...)) (headline (:raw-value "Implement data services" :begin 20358 :end 20514 :pre-blank 1 :contents-begin 20401 :contents-end 20513 ...)) (headline (:raw-value "~restic~ [[path-org-selection:regularbackups.html][backups]] ([[path-org-bash:regularbackups.org][source]])" :begin 156930 :end 162804 :pre-blank 0 :contents-begin 157053 :contents-end 162803 ...)) (headline (:raw-value "~tar~ laptop [[path-org-selection:regularbackups.html][backup]] ([[path-org-bash:regularbackups.org][source]])" :begin 162804 :end 164894 :pre-blank 0 :contents-begin 162930 :contents-end 164893 ...)) (headline (:raw-value "Backup Capco data" :begin 166076 :end 166158 :pre-blank 0 :contents-begin 166123 :contents-end 166157 ...)))
```

I did `M-x toggle-debug-on-error` and ran `M-x org-upcoming-modeline-mode` twice. `*Messages*` says:
```
Org-Upcoming-Modeline mode disabled
Org-Upcoming-Modeline mode enabled
```

**Comment by unhammer** [comment]
And the modeline still says `*invalid*` after restarting it? 

If I add
```
* take backups of house
  <2023-07-04 16:00>
``` 
to an agenda file and try `M-: (org-upcoming-modeline--find-event)`, I get

```
(#s(ts 16 0 0 4 7 2023 nil nil nil nil nil ...) "take backups of house" #<marker at 125 in test.org>)
```
– what do you get?

Also, what is `org-version` and your version of `org-ql`?

**Comment by morgandavidson** [comment]
Yes, `*invalid*` is still shown in the modeline.

If I add:
```
**** MEETING Sophie @ phone
SCHEDULED: <2023-07-04 mar. 17:00>
```
to `meetings.org`, then `M-: (org-upcoming-modeline--find-event)` gives: 
```
(#s(ts 17 0 0 4 7 2023 nil nil nil nil nil ...) "Sophie @ phone" #<marker at 9344 in meetings.org>)
```

`org-ql` version 20230525.1548
`Org mode` version 9.6.5

**Comment by unhammer** [comment]
How odd, that looks perfectly fine (I tried upgarding to that `org-ql` version, no difference. I'm on org 9.6.1, not sure if that matters yet.)

After `M-: (org-upcoming-modeline--find-event)` returns that, does `M-: (org-upcoming-modeline--set-string)` give anything? What's the value of `C-h v org-upcoming-modeline-string`?

**Comment by morgandavidson** [comment]
`(org-upcoming-modeline--set-string)` gives:
```
#(" ⏰ 17:00: Sophie @ phone" 0 24 (face org-upcoming-modeline-normal-face help-echo "1 hours, 34 minutes, 10 seconds left until Sophie @ phone (mouse-1: goto, mouse-2: snooze, mouse-3: menu)" org-upcoming-marker #<marker at 9344 in meetings.org> mouse-face mode-line-highlight local-map (keymap (mode-line keymap ... ... ...))))
```

Then `C-h v org-upcoming-modeline-string`:

```emacs-lisp
org-upcoming-modeline-string is a variable defined in ‘org-upcoming-modeline.el’.

Its value is
#(" ⏰ 17:00: Sophie @ phone" 0 24
  (face org-upcoming-modeline-normal-face help-echo "1 hours, 36 minutes, 46 seconds left until Sophie @ phone (mouse-1: goto, mouse-2: snooze, mouse-3: menu)" org-upcoming-marker #<marker at 9344 in meetings.org> mouse-face mode-line-highlight local-map
	(keymap
	 (mode-line keymap
		    (down-mouse-3 . org-upcoming-modeline-popup-menu)
		    (down-mouse-2 . org-upcoming-modeline-snooze)
		    (down-mouse-1 . org-upcoming-modeline-goto)))))
```

**Comment by unhammer** [comment]
Have you got a special modeline config already? (Are you using doom emacs?)

**Comment by morgandavidson** [comment]
I use standard Emacs (no doom, spacemacs, or such...).

Here is how I configured the modeline:

```emacs-lisp 
  (setq-default mode-line-format
		(list
		 "%Z" ; print mnemonics of keyboard, terminal, and buffer coding systems.
		 " %b " ; print buffer name.
		 "%+ " ; - means buffer it is not modified
					  ; % means buffer is read-only and
					  ; * means buffer is modified.
					  ;	     "%f" ; print visited file name.
					  ;	     "%F" ; print frame name.

					  ;		"%s" ; print process status.
		 "%o" ; print percent of window travel through buffer, or Top, Bot or All.

		 "  Line %l" ; print the current line number.
					  ;	     " %C" ; Like %c, but the leftmost column is displayed as one.
		 "  %I  " ; print the size of the buffer in  k, M, G, etc
		 mode-line-misc-info
		 ))
```

When I comment it, the issue remains. I thought there was a conflict with another package, so I tried with vanilla Emacs, but the issue remains.

**Comment by unhammer** [comment]
This is emacs from git? What revision?

**Comment by morgandavidson** [comment]
GNU Emacs 29.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.17.8) of 2023-05-15. I got it [here](https://lists.gnu.org/archive/html/emacs-devel/2023-05/msg00379.html).

I also have 28.2 that has been installed with `$ sudo pacman -S emacs` and it shows a different error message:

`Error (use-package): org-upcoming-modeline/:catch: Symbol’s function definition is void: oclosure--define Disable showing Disable logging`

**Comment by unhammer** [comment]
I think I found the issue; if `global-mode-string` is nil then enabling org-upcoming-modeline will give it only one element, which is invalid as a Mode Line Construct. (I run with `display-time-mode` which sets a list value for `global-mode-string`.)

Does it fix it on your end?

**Comment by morgandavidson** [comment]
Indeed you found the issue and solved it, thank you! So is it necessary to have the time displayed in the modeline?

Also, a figure now appears, it is 0.57 in [this screenshot](https://paste.pics/OPV9Q), and there is a Unicode error at the beginning of `org-upcoming-modeline-mode` display.


My understanding is that `org-upcoming-modeline-mode` will show the next scheduled `TODO` item having a time slot. How could I restrict the display to `TODO` item with a `MEETING` state?

**Comment by morgandavidson** [comment]
With the following configuration, org-upcoming-modeline-mode works, but it takes 10 to 20 sec to load and there is still an error message at startup:
```emacs-lisp
  (setq display-time-24hr-format t ; set time to 24h format
	display-time-default-load-average nil ; remove load average from time display
	)
  (display-time-mode) ; show time in modeling
  (use-package org-upcoming-modeline
    :after org                               ; if you don't want it to start until org has been loaded
    :config 
    (org-upcoming-modeline-mode) ; show next time scheduled task in modline
    )
```

**Comment by unhammer** [comment]
Newest git should work even with empty global-mode-string, ie. even without display-time-mode. 

You can `(setq org-upcoming-modeline-ignored-keywords '("TODO"))` to exclude that.

It is normal for it to not show immediately – see e.g. org-upcoming-modeline-recompute-after-idle, it only starts looking for events after some idle time, to avoid blocking emacs.

**Comment by morgandavidson** [comment]
Thank you, `setq org-upcoming-modeline-ignored-keywords` works fine:

```emacs-lisp 
  (use-package org-upcoming-modeline
      :after org                               ; if you don't want it to start until org has been loaded
      :config 
      (setq
       org-upcoming-modeline-ignored-keywords '("BACKLOG" "DELEGATED" "NEXT" "RECURRENT" "STARTED" "WAITING")
  ;     org-upcoming-modeline-format (lambda (t h) (format "%s: %s" t h))
  ;     org-upcoming-modeline-format (lambda (t h) (format "%s %s" h t))
       )
      (org-upcoming-modeline-mode) ; show next time scheduled task in the modeline  
      )
```

I got the latest version from Melpa installed ( 0.1.4). Indeed, `org-upcoming-modeline-mode` now works fine even without `(display-time-mode)`. However, I have the following error message each time I start emacs up: `Error (org-ql-select): Not an Org buffer: *scratch*`.

**Comment by unhammer** [comment]
Can you make a new issue on the scratch buffer thing? Not sure when I'll have time to look at it, and it'll get forgotten here
