### ISSUE TITLE
How to remove/replace the alarm clock icon?

### ISSUE THREAD

**Issue by morgandavidson** [unhammer/org-upcoming-modeline#16]
[As it shows a Unicode error in my modeline](https://paste.pics/OPW7M), I'd prefer to remove it or replace it with another symbol if possible.

**Comment by unhammer** [comment]
Grab the newest version and `(setq org-upcoming-modeline-format (lambda (t h) (format "%s: %s" t h)))`
 or even `(setq org-upcoming-modeline-format (lambda (t h) (format "%s %s" h t)))` if you're feeling adventurous

**Comment by morgandavidson** [comment]
I got the latest version from Melpa installed ( 0.1.4), and neither line works. They produce the following error message: `Error running timer ‘org-upcoming-modeline--set-string’: (setting-constant t)`

**Comment by unhammer** [comment]
Or `(setq org-upcoming-modeline-format (lambda (title header) (format "%s: %s" title header)))` ? You can customise it however you want.

**Comment by morgandavidson** [comment]
`(setq org-upcoming-modeline-format (lambda (title header) (format "%s: %s" title header)))` works perfectly, thank you!
