### ISSUE TITLE
Problem with use of pcase macro

### ISSUE THREAD

**Issue by tmalsburg** [unhammer/org-upcoming-modeline#22]
I get this error message with an up-to-date development emacs:

```
Error running timer ‘org-upcoming-modeline--find-event’: (error "Please avoid it")
```

I think this is triggered by `pcase--u1`.  It has a comment (in pcase.el) saying:

```
;; It's very tempting to use `pcase' below, tho obviously, it'd create
;; bootstrapping problems.
```

This happens when I `(require 'org-upcoming-modeline)`, also on  `(org-upcoming-modeline-mode)` and subsequently periodically triggered by the timer.

**Comment by unhammer** [comment]
Odd. Do you happen to have the exact git revision of the emacs version that gives this? (And what version/install method of org-upcoming-modeline?)

Is it reproducible in `emacs -Q` if you eval `(package-initialize)` and `(require 'org-upcoming-modeline)`?

**Comment by tmalsburg** [comment]
Just confirmed it with `emacs -Q`.  MWE:

``` elisp
(defvar bootstrap-version)
(setq straight-repository-branch "develop")
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'ts)
(straight-use-package 'org-ql)
(straight-use-package 'org-upcoming-modeline)

(require 'org-upcoming-modeline)

(org-upcoming-modeline-mode)
```

Using the up-to-date version of org-upcoming-modeline and `GNU Emacs 31.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0) of 2024-09-02` i.e. yesterday's development Emacs, commit: `92ea393a16e5c99a8860dab368c6ca3ca6abc3c5`

Output in buffer `*Compile-Log*`:

```
~/.emacs.d/straight/build/org-ql/org-ql.elc: Error: Please avoid it
~/.emacs.d/straight/build/org-upcoming-modeline/org-upcoming-modeline.el: Error: Please avoid it
```

**Comment by unhammer** [comment]
That is odd! I tried 92ea393a16e5c99a8860dab368c6ca3ca6abc3c5 `GNU Emacs 31.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars) of 2024-09-07` 
and loaded your recipe in the scratch buffer one statement at a time, and saw no such message. I also get no `*Compile-Log*`, but instead I see buffers `*straight-byte-compilation*` and `*Async-native-compile-log*`, neither of which have any lines containing the word `please`.

**Comment by unhammer** [comment]
Do you have zero other settings apart from that recipe above? (Ie. empty org-agenda list, so nothing for org-upcoming-modeline to do.)

I've never used straight before, but I notice it places a folder in .emacs.d, did you delete/move this before running your recipe?

(Also interesting to note that your compile log has the same error from compiling org-ql. I saw https://github.com/alphapapa/org-ql/blob/c3519fb4a072fa24cf5d5b2296a873baf93552a4/org-ql.el#L1121 which may be relevant, though I'm not sure how yet.)

**Comment by tmalsburg** [comment]
No other settings.  Just `emacs -Q` and the elisp code quoted above.  I used `eval-buffer` to run the code.  Straight doesn't load anything else but itself.  In fact the author writes that one of the major reasons for developing straight was precisely to make debugging packages easier.  Having said that: After deleting the `straight` subdirectory, I could no longer reproduce the problem.  Sorry for the noise.

**Comment by unhammer** [comment]
I think maybe `emacs -Q --init-directory=/tmp/something` might be safer for clean reproductions (iiuc you then use /tmp/something as .emacs.d), though I haven't tried

**Comment by tmalsburg** [comment]
Thanks for the pointer, I keep forgetting that `--init-directory` exists.
