### ISSUE TITLE
Recurring events are not displayed

### ISSUE THREAD

**Issue by tmalsburg** [unhammer/org-upcoming-modeline#5]
Great package but unfortunately, recurring events do not show up.  For instance, the following event is displayed only the first time:
```
** Weekly meeting
  <2018-10-17 Wed 12:00-14:00 +1w>
```

**Comment by swflint** [comment]
Fwiw, for weekly items, I've found that using `org-clone-subtree-with-time-shift` (`C-c C-x c`) is somewhat more helpful than using repeaters.  I have a suspicion, however, that this may have something to do with how `org-ql` handles repeaters.

**Comment by tmalsburg** [comment]
I have a lot of weekly meetings and some of them go on for years.  Making individual instances is therefore less attractive.  More work, more room for errors, larger org files.

I’ve made a feature request at org-ql, see here: https://github.com/alphapapa/org-ql/issues/159

**Comment by tmalsburg** [comment]
It's working now :) This is one the those small things that can make a big difference.  Thank you so much!

**Comment by unhammer** [comment]
Thank you for reporting and testing :-)
