### ISSUE TITLE
Error running timer ‘org-upcoming-modeline--find-event’:

### ISSUE THREAD

**Issue by tmalsburg** [unhammer/org-upcoming-modeline#9]
Since today or yesterday, I'm getting this error and nothing is showing in the mode line:
```
Error running timer ‘org-upcoming-modeline--find-event’: (wrong-type-argument ts nil) [3 times]
```

**Comment by unhammer** [comment]
Oh sorry I forgot to check the case of no matches. Should probably make some tests …
Could you check if a1bc82983454bca5738551be1b2e7d62229ccc52 solves it?

**Comment by tmalsburg** [comment]
Thanks.  But I can't test it because the problem doesn't occur anymore and I don't know how to reproduce it.  Suggestions?

**Comment by unhammer** [comment]
I reproduced when I didn't have any upcoming events. But I'll close for now and we can reopen if it seems it wasn't solved.

**Comment by tmalsburg** [comment]
Thank you.
